//打印欢迎界面
require('colors')
module.exports = () => {
    console.log('                  这种感觉还行嘛'.yellow)
    console.log('                      .::::.'.red)
    console.log('                    .::::::::.'.red)
    console.log('                   :::::::::::'.red)
    console.log('                ..:::::::::::\''.red)
    console.log('             \'::::::::::::\''.red)
    console.log('               .::::::::::'.red)
    console.log('          \'::::::::::::::..'.red)
    console.log('               ..::::::::::::.'.red)
    console.log('             ``::::::::::::::::'.red)
    console.log('              ::::``:::::::::\'        .:::.'.red)
    console.log('             ::::\'   \':::::\'       .::::::::.'.red)
    console.log('           .::::\'      ::::     .:::::::\'::::.'.red)
    console.log('          .:::\'       :::::  .:::::::::\' \':::::.'.red)
    console.log('         .::\'        :::::.:::::::::\'      \':::::.'.red)
    console.log('        .::\'         ::::::::::::::\'         ``::::.'.red)
    console.log('    ...:::           ::::::::::::\'              ``::.'.red)
    console.log('   ```` \':.          \':::::::::\'                  ::::..'.red)
    console.log('                      \'.:::::\'                    \':\'````..'.red)
}